image: node:latest

stages:
  - install
  - test
  - build

Install dependencies:
  stage: install
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  script:
    - npm install
  artifacts:
    paths:
      - ./node_modules

Run checks and lint:
  stage: test
  script:
    - npm run lint

Run tests:
  stage: test
  script:
    - npm run test

Build app:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - ./build
