image: node:latest

stages:
  - install
  - test
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
  policy: pull

Install dependencies:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - ./node_modules

Run checks and lint:
  stage: test
  script:
    - npm run lint

Run tests:
  stage: test
  script:
    - npm run test

Build app:
  stage: build
  environment:
    name: review/$CI_COMMIT_REF_NAME
  script:
    - npm run build
  artifacts:
    paths:
      - ./build

.aws_sync:
  stage: deploy
  script: |
    pip install awscli
    aws s3 sync ./build/ s3://${BUCKET_DEV}

Prod Deploy:
  stage: deploy
  extends: .aws_sync
  before_script: -export S3_BUCKET=${BUCKET_DEV}
