image: node:latest

stages:
  - install
  - test
  - build

Install dependencies:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - ./node_modules

Run checks:
  stage: test
  script:
    - npm run lint

Run tests:
  stage: test
  script:
    - npm run test

Build app:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - ./build

test server:
  stage: build
  script:
    - npm lint
    - curl "http://localhost:3000" | grep -q "Testing run"
