image: node:latest

stages:
  - install
  - test
  - build

Install dependencies:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

Run tests:
  stage: test
  script:
    - npm run test

Build app:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - build/
