### File setup
image: node:latest

variables:
  ARTIFACT_NAME: build-v${CI_PIPELINE_IID}
  EBS_APP_NAME: gitlab-learner

stages:
  - install
  - test
  - build
  - review
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
  policy: pull

.aws_sync:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script: 
  - aws s3 sync ./build/ s3://${REVIEW_BUCKET_NAME}/${ARTIFACT_NAME}
  - aws elasticbeanstalk create-application-version --application-name ${EBS_APP_NAME} --version-label $CI_PIPELINE_IID --source-bundle S3Bucket=${REVIEW_BUCKET_NAME},S3Key=${ARTIFACT_NAME}
  - aws elasticbeanstalk update-environment --application_name ${EBS_APP_NAME} --environment-name "production" --version-label $CI_PIPELINE_IID

### Stages
# - add aggressive cache unless dependencies change
Install dependencies:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - ./node_modules

Run checks and lint:
  stage: test
  script:
    - npm run lint

Run tests:
  stage: test
  script:
    - npm run test

Build app:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - ./build

Review Deploy:
  stage: review
  extends: .aws_sync
  only:
    - branches
  environment:
    name: review/$CI_COMMIT_REF_NAME
  before_script:
    - export S3_BUCKET=${REVIEW_BUCKET_NAME}
  only:
    - ^review/

Staging Deploy:
  stage: deploy
  environment:
    name: Beta
  extends: .aws_sync
  before_script:
    - export S3_BUCKET=${REVIEW_BUCKET_NAME}
  only:
    - develop

Prod Deploy:
  stage: deploy
  environment:
    name: Production
  # when: manual
  extends: .aws_sync
  before_script:
    - export S3_BUCKET=${REVIEW_BUCKET_NAME}
  only:
    - master
