image: node:latest

.push-and-deploy:
  image: "registry.gitlab.com/gitlab-org/cloud-deploy/aws-ec2:latest"
  script:
    - gl-ec2 push-to-s3
    - gl-ec2 deploy-to-ec2

stages:
  - install
  - test
  - build
  - deploy staging

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
  policy: pull

Install dependencies:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - ./node_modules

Run checks and lint:
  stage: test
  script:
    - npm run lint

Run tests:
  stage: test
  script:
    - npm run test

Build app:
  extends: .push-and-deploy
  stage: build
  environment:
    name: review/$CI_COMMIT_REF_NAME
  script:
    - npm run build
  artifacts:
    paths:
      - ./build
  rules:
    - if: '$AUTO_DEVOPS_PLATFORM_TARGET != "EC2"'
      when: never
    - if: "$CI_KUBERNETES_ACTIVE"
      when: never
    - if: "$REVIEW_DISABLED"
      when: never
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
      when: never
    - if: "$CI_COMMIT_TAG || $CI_COMMIT_BRANCH"
