### File setup
image: node:latest

stages:
  - install
  - test
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
  policy: pull

.aws_sync:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script: aws s3 sync ./build/ s3://${BUCKET_DEV}

### Stages
Install dependencies:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - ./node_modules

Run checks and lint:
  stage: test
  script:
    - npm run lint

Run tests:
  stage: test
  script:
    - npm run test

Build app:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - ./build

Staging Deploy:
  stage: deploy
  environment:
    name: Beta
  extends: .aws_sync
  before_script:
    - export S3_BUCKET=${BUCKET_DEV}

Prod Deploy:
  stage: deploy
  environment:
    name: Production
  when: manual
  extends: .aws_sync
  before_script:
    - export S3_BUCKET=${BUCKET_DEV}
  only:
    - master
